install:
  - gem install taskjuggler
  - gem install rake rspec

script:
  - tj3 -o reports Umzug.tjp"
#  - rake

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: reports
  on:
    branch: master
