install:
  - gem install taskjuggler

script:
   - 'rake --trace'
#  - tj3 Umzug.tjp


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: reports
  on:
    branch: master
